name: perf tests in docker
on:
  push:

env:
  OPAMROOT: /home/user/.opam
  OPAMCONFIRMLEVEL: unsafe-yes

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: trickyfoxy/lama_truffle

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - run: opam --version
      - run: whoami
      - run: opam exec -- ocamlopt --version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: build truffle
        timeout-minutes: 10
        run: mvn package -Pnative

      - name: run perf tests
        timeout-minutes: 10
        run: bash -c "time ./launcher/target/lama tests/performance/Sort.lama"

      - name: run perf tests for lamac
        timeout-minutes: 10
        run: lamac tests/performance/Sort.lama && bash -c "time ./Sort"
